postgres:
  image: postgres:latest
  container_name: postgres
  environment:
    - "TZ=Europe/Amsterdam"
    - "POSTGRES_USER=docker"
    - "POSTGRES_PASSWORD=docker"
  ports:
    - "5432:5432"  # credentials (docker:docker)

mysql:
  image: mysql:latest
  container_name: mysql
  environment:
    - "TZ=Europe/Amsterdam"
    - "MYSQL_ROOT_PASSWORD=root"
  ports:
    - "3306:3306" # credentials (root:root)

#oracle:
#  image: sath89/oracle-12c
#  container_name: oracle
#  environment:
#    - "TZ=Europe/Amsterdam"
#    - "DBCA_TOTAL_MEMORY=1024"
#    - "WEB_CONSOLE=false" # disable web console (APEX)
#  ports:
#    - "1521:1521" # DB_CONN: credentials (system:oracle)
#    - "8080:8080" # APEX: credentials (ADMIN:0Racle$)